print("Ingresa tu nombre: ")
nombre = input()
print("Ingresa tu apellido: ")
apellido = input()
print("Ingresa tu edad: ")
edad = input()
print("Ingresa tu lugar de residencia: ")
residencia = input()

print(f"Soy {nombre} {apellido}, tengo {edad} años y vivo en {residencia}.")
